ALTER TABLE devices
  ADD COLUMN IF NOT EXISTS chip_type VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS chip_family VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS flash_size VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS crystal_freq VARCHAR(20) DEFAULT NULL;
